language: node_js
node_js:
  - '10'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
before_script:
  - sleep 15
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm run lint
  - DB_USER=travis DB_PASS=test MONGO_URL=mongodb://127.0.0.1:27017/test npm run cover
